---
title: "Reference Manual"
output: 
  # rmarkdown::html_vignette:
  BiocStyle::html_document:
    toc: true
    toc_depth: 2
  # html_document:
  #   toc: true
  #   toc_float: true
  #   highlight: kate
author: "Søren Helweg Dam"
date: "Last updated on July 18, 2022"
vignette: >
  %\VignetteIndexEntry{Reference Manual}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(pairedGSEA)

example_data <- example_data


results <- pairedGSEA::paired_de(
    tx_count = example_data$tx_count,
    metadata = example_data$metadata,
    group_col = "group_nr",
    sample_col = "id",
    baseline = 1,
    case = 2,
    experiment_title = "TNF Treatment 12hrs",
    store_results = FALSE,
    quiet = FALSE
  )


```


```{r}
gene_sets <- pairedGSEA::prepare_msigdb()
results_ora <- paired_ora(results, gene_sets)#, universe = c(results$gene, 1:14000))

```


```{r}
results_ora2 <- results_ora %>% mutate(padj_deseq = pval_deseq,
                                       padj_dexseq = pval_dexseq)
plot_ora(results_ora2, pattern = "Telomer")

```

